import { prisma } from '../../config/db.js';
import { AIResultType } from '@prisma/client';
import { getCache, setCache } from '../../services/redis.service.js';
import { logger } from '../../config/logger.js';
import { env } from '../../config/env.js';
import crypto from 'crypto';

type StructuredAIResponse = {
  summary: string;
  details: string[];
  recommendations: string[];
};

const GEMINI_MODEL = 'gemini-2.0-flash';

function estimateTokens(...segments: string[]) {
  const text = segments.join(' ');
  return Math.max(1, Math.ceil(text.length / 4));
}

function fallbackReasonLabel(reason: string) {
  return reason === 'quota_exceeded'
    ? 'The live AI provider hit its quota limit.'
    : 'The live AI provider was unavailable.';
}

function buildInterviewFallbackReply(prompt: string, reason: string): StructuredAIResponse {
  const lowerPrompt = prompt.toLowerCase();

  if (lowerPrompt.includes('react') && lowerPrompt.includes('next') && lowerPrompt.includes('typescript')) {
    return {
      summary: 'Great. First technical question: In a Next.js app using React and TypeScript, how would you explain the difference between Server Components and Client Components, and when would you choose one over the other?',
      details: [
        fallbackReasonLabel(reason),
        'You provided enough frontend stack context to ask a targeted Next.js question.',
        'This fallback is intentionally acting like a real interviewer rather than an analysis tool.',
      ],
      recommendations: [
        'Answer in a structured way: definition, tradeoff, and practical example.',
        'Mention rendering, bundle size, and access to browser APIs.',
        'Use a concrete feature from a real project if you can.',
      ],
    };
  }

  if (lowerPrompt.includes('frontend')) {
    return {
      summary: 'Let’s start with a frontend architecture question: how do you decide when state should stay local to a component, move into context, or be handled by a client-state library?',
      details: [
        fallbackReasonLabel(reason),
        'The role context points to frontend engineering, so the question is aimed at practical UI architecture.',
        'This response is generated by the backend fallback layer, not Gemini.',
      ],
      recommendations: [
        'Compare scope, update frequency, and cross-component sharing.',
        'Mention performance and maintainability tradeoffs.',
        'Give one example from React or Next.js.',
      ],
    };
  }

  return {
    summary: 'Before we start, tell me the exact role, level, and stack you want to practice for, and then I will ask you the first technical interview question.',
    details: [
      fallbackReasonLabel(reason),
      'The interview fallback needs a little more context to ask a useful question.',
      'Once role and stack are clear, it can behave more like a live mock interviewer.',
    ],
    recommendations: [
      'Mention the role title.',
      'Mention the stack you want questions on.',
      'Mention whether you want junior, mid, or senior difficulty.',
    ],
  };
}

function buildResumeFallback(prompt: string, reason: string): StructuredAIResponse {
  const hasResumeExcerpt = prompt.includes('Resume excerpt:');

  if (!hasResumeExcerpt) {
    return {
      summary: 'I cannot give a trustworthy resume analysis yet because the backend did not receive actual resume text, only metadata like the target role or filename.',
      details: [
        fallbackReasonLabel(reason),
        'A filename alone is not enough to evaluate bullets, structure, keywords, or clarity.',
        'Resume analysis should be based on extracted document content, not just the uploaded file name.',
      ],
      recommendations: [
        'Extract and send real resume text before asking for ATS feedback.',
        'Then evaluate quantified outcomes, keyword match, and section clarity.',
        'Until that is in place, treat any detailed verdict as unreliable.',
      ],
    };
  }

  return {
    summary: reason === 'quota_exceeded'
      ? 'I received resume text, but the live AI provider is temporarily over quota, so this is a limited fallback review.'
      : 'I received resume text, but the live AI provider was unavailable, so this is a limited fallback review.',
    details: [
      'Resume content was present in the request, which means the pipeline is closer to a real analysis now.',
      'This fallback cannot replace a full model review, but it can still guide the next edit.',
      'Focus first on measurable outcomes, keyword alignment, and stronger ownership language.',
    ],
    recommendations: [
      'Add one quantified outcome to each recent role.',
      'Mirror the target role language more directly in skills and project bullets.',
      'Shorten the summary and make the positioning clearer.',
    ],
  };
}

const fallbackResponses: Record<AIResultType, (prompt: string, reason: string) => StructuredAIResponse> = {
  RESUME: (prompt, reason) => buildResumeFallback(prompt, reason),
  ROADMAP: (prompt, reason) => ({
    summary: 'The next step is to narrow the role, identify missing skills, and build a staged learning plan.',
    details: [
      fallbackReasonLabel(reason),
      `Roadmap context received: ${prompt.substring(0, 80)}...`,
      'Break the transition into foundation, project practice, and interview readiness.',
    ],
    recommendations: [
      'List the top 3 missing skills for your target role.',
      'Build one portfolio project that proves those skills.',
      'Review job listings weekly and refine the roadmap from fresh demand signals.',
    ],
  }),
  INTERVIEW: (prompt, reason) => buildInterviewFallbackReply(prompt, reason),
  SKILL_GAP: (prompt, reason) => ({
    summary: 'Your gap analysis should focus on missing tools, depth of experience, and proof of execution.',
    details: [
      fallbackReasonLabel(reason),
      `Skill-gap context received: ${prompt.substring(0, 80)}...`,
      'Most gaps come from either missing fundamentals or lack of visible project evidence.',
    ],
    recommendations: [
      'Separate hard-skill gaps from proof-of-work gaps.',
      'Pick one missing skill to study and one artifact to build this week.',
      'Use job descriptions to validate whether the gap is actually important.',
    ],
  }),
  COVER_LETTER: (prompt, reason) => ({
    summary: 'A strong cover letter should connect your experience to the role in a direct, specific way.',
    details: [
      fallbackReasonLabel(reason),
      `Cover-letter context received: ${prompt.substring(0, 80)}...`,
      'Lead with fit, not biography.',
    ],
    recommendations: [
      'Open with why this role makes sense for you now.',
      'Add one quantified example from recent work.',
      'Close with a simple, confident expression of interest.',
    ],
  }),
};

function buildSystemInstruction(type: AIResultType) {
  switch (type) {
    case 'INTERVIEW':
      return [
        'You are an expert AI interview coach.',
        'Respond like a live mock interviewer or coach, not like a system status message.',
        'Always return strict JSON with keys: summary, details, recommendations.',
        'For INTERVIEW, the summary must be the actual conversational reply the user should see next.',
        'details should contain 2-4 short observations about the interview context.',
        'recommendations should contain 2-4 short next-step suggestions.',
        'Never prefix the answer with "Mock".',
      ].join(' ');
    case 'RESUME':
      return [
        'You are an expert resume reviewer.',
        'Always return strict JSON with keys: summary, details, recommendations.',
        'summary should be one concise overall judgment.',
        'details should list specific findings.',
        'recommendations should list concrete edits.',
      ].join(' ');
    case 'ROADMAP':
      return [
        'You are an expert career roadmap coach.',
        'Always return strict JSON with keys: summary, details, recommendations.',
        'summary should describe the overall path.',
        'details should list key roadmap stages.',
        'recommendations should list the next concrete actions.',
      ].join(' ');
    case 'SKILL_GAP':
      return [
        'You are an expert skill-gap analyst.',
        'Always return strict JSON with keys: summary, details, recommendations.',
        'summary should describe the main gap.',
        'details should explain the specific missing areas.',
        'recommendations should be practical next steps.',
      ].join(' ');
    case 'COVER_LETTER':
      return [
        'You are an expert cover-letter coach.',
        'Always return strict JSON with keys: summary, details, recommendations.',
        'summary should describe the overall letter strategy.',
        'details should explain what content to include.',
        'recommendations should list concrete writing improvements.',
      ].join(' ');
  }
}

function normalizeStructuredResponse(value: unknown, type: AIResultType, prompt: string): StructuredAIResponse {
  if (!value || typeof value !== 'object') {
    return fallbackResponses[type](prompt, 'provider_unavailable');
  }

  const candidate = value as Partial<StructuredAIResponse>;
  const summary = typeof candidate.summary === 'string' && candidate.summary.trim()
    ? candidate.summary.trim()
    : fallbackResponses[type](prompt, 'provider_unavailable').summary;
  const details = Array.isArray(candidate.details) ? candidate.details.map(String).filter(Boolean) : fallbackResponses[type](prompt, 'provider_unavailable').details;
  const recommendations = Array.isArray(candidate.recommendations)
    ? candidate.recommendations.map(String).filter(Boolean)
    : fallbackResponses[type](prompt, 'provider_unavailable').recommendations;

  return { summary, details, recommendations };
}

async function callGemini(prompt: string, type: AIResultType): Promise<StructuredAIResponse> {
  if (!env.GEMINI_API_KEY) {
    return fallbackResponses[type](prompt, 'provider_unavailable');
  }

  const response = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent?key=${env.GEMINI_API_KEY}`,
    {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        systemInstruction: {
          parts: [{ text: buildSystemInstruction(type) }],
        },
        contents: [
          {
            role: 'user',
            parts: [{ text: prompt }],
          },
        ],
        generationConfig: {
          temperature: type === 'INTERVIEW' ? 0.8 : 0.4,
          responseMimeType: 'application/json',
        },
      }),
    }
  );

  if (!response.ok) {
    const text = await response.text();
    logger.error('Gemini API request failed', { status: response.status, type, body: text.substring(0, 300) });
    const reason = response.status === 429 ? 'quota_exceeded' : 'provider_unavailable';
    return fallbackResponses[type](prompt, reason);
  }

  const data = await response.json() as {
    candidates?: Array<{
      content?: {
        parts?: Array<{ text?: string }>;
      };
    }>;
  };

  const rawText = data.candidates?.[0]?.content?.parts?.map((part) => part.text ?? '').join('').trim();
  if (!rawText) {
    logger.warn('Gemini API returned empty content', { type });
    return fallbackResponses[type](prompt, 'provider_unavailable');
  }

  try {
    const parsed = JSON.parse(rawText);
    return normalizeStructuredResponse(parsed, type, prompt);
  } catch (error) {
    logger.warn('Gemini response was not valid JSON, applying fallback parser', {
      type,
      error: error instanceof Error ? error.message : 'Unknown parse error',
    });
    return fallbackResponses[type](prompt, 'provider_unavailable');
  }
}

export const processAIRequest = async (userId: string, type: AIResultType, prompt: string) => {
  const hash = crypto.createHash('md5').update(prompt + userId).digest('hex');
  const cacheKey = `ai:v2:${type}:${hash}`;

  const cachedResponse = await getCache(cacheKey);
  if (cachedResponse) {
    logger.info('AI cache hit', { userId, type, cacheKey });
    await prisma.aIUsageLog.create({
      data: {
        userId,
        feature: type,
        tokensUsed: estimateTokens(prompt, JSON.stringify(cachedResponse)),
        responseTime: 0,
        success: true,
      },
    });
    return cachedResponse;
  }

  const start = Date.now();
  const response = await callGemini(prompt, type);
  const latencyMs = Date.now() - start;

  logger.info('AI request processed', { userId, type, latencyMs, promptLength: prompt.length });

  const tokensUsed = estimateTokens(prompt, response.summary, response.details.join(' '), response.recommendations.join(' '));

  await prisma.aIResult.create({
    data: { userId, type, prompt, response },
  });

  await prisma.aIUsageLog.create({
    data: {
      userId,
      feature: type,
      tokensUsed,
      responseTime: latencyMs,
      success: !response.details.some((detail) => detail.toLowerCase().includes('provider was unavailable') || detail.toLowerCase().includes('quota limit')),
    },
  });

  await setCache(cacheKey, response, 3600);
  return response;
};

export const getUserAIResults = async (userId: string) => {
  return prisma.aIResult.findMany({
    where: { userId },
    orderBy: { createdAt: 'desc' },
  });
};

export const deleteAIResult = async (id: string, userId: string) => {
  const result = await prisma.aIResult.findUnique({ where: { id } });
  if (!result || result.userId !== userId) {
    throw { statusCode: 404, message: 'Result not found or forbidden' };
  }
  await prisma.aIResult.delete({ where: { id } });
  return null;
};
